### ISSUE TITLE
put agentNote into the premis namespace

### ISSUE THREAD

**Issue by flazz** [fcla/xmlresolution#10]
currently agentNote is in `info:lc/xmlns/premis-v2-beta` please use `info:lc/xmlns/premis-v2` as that element is available in the schema now.

**Comment by grf** [comment]
already done, won't push out for a while unless critical (repoen
if that's the case)

please let me know which hosts you are using.

**Comment by grf** [comment]
bit the bullet - deployed to the usual places.
