### ISSUE TITLE
bad status: 500 -- Internal Service Error while processing E58UXD5MI_KBCGJR

### ISSUE THREAD

**Issue by cchou** [fcla/xmlresolution#11]
bad status: 500 -- Internal Service Error.
http://xmlresolution.fda.fcla.edu/ieids/E58UXD5MI_KBCGJR/: 500
Internal Service Error.
trace  
./lib/mixin/curb.rb:10:in `error'
./lib/daitss/service/xmlres.rb:22:in`resolve_file'
./lib/daitss/proc/wip/preserve.rb:35:in `preserve'
./lib/daitss/proc/wip/preserve.rb:34:in`each'
./lib/daitss/proc/wip/preserve.rb:34:in `preserve'
./lib/daitss/proc/wip/journal.rb:14:in`step'
./lib/daitss/proc/wip/preserve.rb:30:in `preserve'
./lib/daitss/proc/wip/ingest.rb:29:in`ingest'
./lib/daitss/proc/wip/process.rb:65:in `send'
./lib/daitss/proc/wip/process.rb:65:in`spawn'
./lib/daitss/proc/wip/process.rb:55:in `fork'
./lib/daitss/proc/wip/process.rb:55:in`spawn'
./app.rb:357:in `POST /workspace/:id'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:1057:in`call'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:1057:in `compile!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:643:in`instance_eval'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:643:in `route_eval'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:627:in`route!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:675:in `process_route'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:672:in`catch'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:672:in `process_route'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:626:in`route!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:625:in `each'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:625:in`route!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:760:in `dispatch!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:553:in`call!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in `instance_eval'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in`invoke'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in `catch'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in`invoke'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:553:in `call!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:538:in`call'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:608:in `forward'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:689:in`route_missing'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:638:in `route!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:634:in`route!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:760:in `dispatch!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:553:in`call!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in `instance_eval'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in`invoke'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in `catch'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:725:in`invoke'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:553:in `call!'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:538:in`call'
/opt/ruby/gem-repos/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/opt/ruby/gem-repos/gems/rack-1.2.1/lib/rack/methodoverride.rb:24:in`call'
/opt/ruby/gem-repos/gems/rack-1.2.1/lib/rack/commonlogger.rb:18:in `call'
/opt/ruby/gem-repos/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in`call'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:1167:in `call'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:1193:in`synchronize'
/opt/ruby/gem-repos/gems/sinatra-1.1.2/lib/sinatra/base.rb:1167:in `call'
/usr/local/passenger/lib/phusion_passenger/rack/request_handler.rb:92:in`process_request'
/usr/local/passenger/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/usr/local/passenger/lib/phusion_passenger/rack/application_spawner.rb:118:in`run'
/usr/local/passenger/lib/phusion_passenger/rack/application_spawner.rb:65:in `spawn_application'
/usr/local/passenger/lib/phusion_passenger/utils.rb:184:in`safe_fork'
/usr/local/passenger/lib/phusion_passenger/rack/application_spawner.rb:58:in `spawn_application'
/usr/local/passenger/lib/phusion_passenger/rack/application_spawner.rb:41:in`spawn_application'
/usr/local/passenger/lib/phusion_passenger/spawn_manager.rb:159:in `spawn_application'
/usr/local/passenger/lib/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
/usr/local/passenger/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/local/passenger/lib/phusion_passenger/abstract_server.rb:352:in`main_loop'
/usr/local/passenger/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/local/passenger/bin/passenger-spawn-server:61

The package is on daitsstest@tarchive.

**Comment by grf** [comment]
UF Lib site http://www.uflib.ufl.edu/digital/metadata/ufdc2/ is hanging on connections; a connection timeout is eventually raised.   XmlResolution was doing a

```
rescue => e
```

Which captures StandardError; Timeout::Error is not a StandardError.  We now catch

```
rescue Exception => e
```

and handle this case.

Fixed and deployed to darchive.fcla.edu.
