### ISSUE TITLE
Internal data should be saved by hash of filename, not contents

### ISSUE THREAD

**Issue by grf** [fcla/xmlresolution#14]
XML files with identical contents for a given collection ID will be inadvertently de-dupped.  Internally, a record of the schemas retrieved for an XML file are stored using a key generated by  a hash of the contents of the file.

Instead, use the name of the file.  We'll have to make sure that ingest is using the entire relative path of the SIP file, when it requests a resolution.

Very low priority.

**Comment by iterman** [comment]
XMLRESOLUTION code was modified to address this issue.  Xmlresolution knows when a schema, DTD, or PI has changed when filesystem date time stamp is different from the stored date time stamp.

**Comment by lydiam** [comment]
This results in the md5sum in the manifest being caculated on the full URI of the schema.  Formerly it had been calculated on the file contents.

**Comment by lydiam** [comment]
Was the intention here to modify the schema checksum in the manifest file?  A checksum computed on the URI doesn't seem to make sense in the context of the manifest.  I would expect that the checksum in the manifest would be the checksum calculated on the contents, and that the routine to determine if the correct file is downloaded would not affect the manifest.  Why are these two tied together?  This is not really making sense to me.

**Comment by lydiam** [comment]
The hash value should incorporate both filename and content.  Note that this value cannot be used in the manifest. (see #22 for the unintended problem caused by this code change).

**Comment by childree** [comment]
Was this code pushed out to ripple and tested prior to being rolled out on fclnx30?

**Comment by lydiam** [comment]
Presumably unit tests were run by Ira prior to pushing the code out to 
ripple.  Ripple Ops testing didn't reveal any problems beyond that 
reported in #22.

**Comment by iterman** [comment]
this issue (#14) and issue #22 are the same.  comments will be put in #22

**Comment by lydiam** [comment]
This code was updated on ripple.  I'm not sure how to compute md5(md5(contents)+location) to test this.

**Comment by iterman** [comment]
Lydia,
1.  first get the contents into a file.
2.  get the md5 of the contents
3.  append the location to the end of the md5
   4 .  md5  the string in number 3.

Ira

**Comment by lydiam** [comment]
Testing on the daitss schema:

[lydiam@ripple workspace]$ touch hash_test2.txt
[lydiam@ripple workspace]$ echo a2aa0a4a13503457317d2a94a4e8b038 > hash_test2.txt
[lydiam@ripple workspace]$ echo -n a2aa0a4a13503457317d2a94a4e8b038 > hash_test2.txt
[lydiam@ripple workspace]$ echo -n http://www.fcla.edu/dls/md/daitss/daitss.xsd >> hash_test2.txt
[lydiam@ripple workspace]$ md5sum hash_test2.txt
fdadfc0c3ec58b5b401fc9dc600a8450  hash_test2.txt

This matches the  filename d20121120-10998-f4h3it/schemas/fdadfc0c3ec58b5b401fc9dc600a8450

This looks to be correct.

**Comment by lydiam** [comment]
Ready for production.
