### ISSUE TITLE
bad status from xmlresolution.

### ISSUE THREAD

**Issue by cchou** [fcla/xmlresolution#16]
d1refresh of E20060113_AAAAAA ( snafu )
snafu

time    Thu Mar 17 12:27:20 -0400 2011
message 
bad status
http://xmlresolution.fda.fcla.edu/ieids/E20060113_AAAAAA: 500

with message from passenger,

Ruby (Rack) application could not be started

**Comment by grf** [comment]
rack gem mismatch on darchive. fixed.
