### ISSUE TITLE
Meaning of xmlresolution AIP premis eventOutcome "mixed", "success", "failure"?

### ISSUE THREAD

**Issue by lydiam** [fcla/xmlresolution#18]
I see an example of a package with an AIP descriptor that includes an xmlresolution event with an eventOutcome of "mixed" which seems to be inconsistent with other xmlresolution premis events.

The package is E9EVL2UR3_ROXHT6.

The daitss_db.broken_links table includes:

```
 192 | http://www.loc.gov/mods/v3/mods-3-3.xsd                                            | info:fda/E9EVL2UR3_ROXHT6/file/0
```

(file/0 - the descriptor - has a mods-3-3.xsd broken link)

The xmlres-0.tar manifest includes the following for the descriptor links:

```
 <schema status="success" last_modified="2009-01-21T17:06:40-05:00" md5="bf97e27bdd02f7031a8a71ea4d229daf" location="http://www.w3.org/2001/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>
 <schema status="success" last_modified="2004-03-20T07:53:09-05:00" md5="94ed1a93ce3147d01bcb2fc1126255ed" location="http://www.w3.org/2001/XMLSchema.xsd" namespace="http://www.w3.org/2001/XMLSchema"/>
 <schema status="failure" message="404 "Not Found"" location="http://www.loc.gov/mods/v3/mods-3-3.xsd" namespace="http://www.loc.gov/mods/v3"/>
```

The AIP descriptor says:

```
 <eventIdentifierValue>info:fda/E9EVL2UR3_ROXHT6/file/0/event/xmlresolution</eventIdentifierValue></eventIdentifier>  
 <eventType>XML Resolution</eventType><eventDateTime>2011-04-30T07:45:21-04:00</eventDateTime>  
 <eventOutcomeInformation><eventOutcome>mixed</eventOutcome><eventOutcomeDetail>
 <eventOutcomeDetailExtension><broken_link>http://www.loc.gov/mods/v3/mods-3-3.xsd</broken_link>
 </eventOutcomeDetailExtension></eventOutcomeDetail>
```

What does  eventOutcome mixed mean?  Does that indicate that xmlresolution for file/0 included manifest schema statuses of "success" and "failure" for the same file?

What are all of the possible eventOutcomes for xlmresolution?  So far I've seen:

"failure" - when one schema resulted in a broken link and one schema resulted in an unresolved namespace (see EXOH703YH_EVVYJZ for an example)
"success" - when the manifest.xml for xmlres-0.tar includes a number of successes for the descriptor schemas and one unresolved namespace (see EONE3XTEQ_U2F0W0):

```
 <schema status="success" location="http://www.w3.org/2001/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace" md5="bf97e27bdd02f7031a8a71ea4d229daf" last_modified="2009-01-21T17:06:40-05:00"/>
 <schema status="success" location="http://www.w3.org/2001/XMLSchema.xsd" namespace="http://www.w3.org/2001/XMLSchema" md5="94ed1a93ce3147d01bcb2fc1126255ed" last_modified="2004-03-20T07:53:09-05:00"/>
 <schema status="unresolved" namespace="http://purl.org/dc/terms/"/>
```

I would appreciate clarification on xmlresolution eventOutcome in the AIP descriptor (presumably xmlresolution writes the AIP descriptor snippet) to help me spec out changes for unresolved namespaces.

**Comment by cchou** [comment]
On Thu, May 31, 2012 at 3:56 PM, Lydia Motyka
reply@reply.github.com
wrote:

> I see an example of a package with an AIP descriptor that includes an xmlresolution event with an eventOutcome of "mixed" which seems to be inconsistent with other xmlresolution premis events.
> 
> The package is E9EVL2UR3_ROXHT6.
> 
> The daitss_db.broken_links table includes:
> 
>     192 | http://www.loc.gov/mods/v3/mods-3-3.xsd                                            | info:fda/E9EVL2UR3_ROXHT6/file/0
> 
> (file/0 - the descriptor - has a mods-3-3.xsd broken link)
> 
> The xmlres-0.tar manifest includes the following for the descriptor links:
> 
>     <schema status="success" last_modified="2009-01-21T17:06:40-05:00" md5="bf97e27bdd02f7031a8a71ea4d229daf" location="http://www.w3.org/2001/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>
>     <schema status="success" last_modified="2004-03-20T07:53:09-05:00" md5="94ed1a93ce3147d01bcb2fc1126255ed" location="http://www.w3.org/2001/XMLSchema.xsd" namespace="http://www.w3.org/2001/XMLSchema"/>
>     <schema status="failure" message="404 "Not Found"" location="http://www.loc.gov/mods/v3/mods-3-3.xsd" namespace="http://www.loc.gov/mods/v3"/>
> 
> The AIP descriptor says:
> 
>     <eventIdentifierValue>info:fda/E9EVL2UR3_ROXHT6/file/0/event/xmlresolution</eventIdentifierValue></eventIdentifier>
>     <eventType>XML Resolution</eventType><eventDateTime>2011-04-30T07:45:21-04:00</eventDateTime>
>     <eventOutcomeInformation><eventOutcome>mixed</eventOutcome><eventOutcomeDetail>
>     <eventOutcomeDetailExtension><broken_link>http://www.loc.gov/mods/v3/mods-3-3.xsd</broken_link>
>     </eventOutcomeDetailExtension></eventOutcomeDetail>
> 
> What does  eventOutcome mixed mean?  Does that indicate that xmlresolution for file/0 included manifest schema statuses of "success" and "failure" for the same file?

I think so,  I remember that's what it was discussed.  Mix means that
for a xml file, some schema can be retrieved and some can't.

However, I am not able to find a spec about the eventOutcome for xmlresolution.

> What are all of the possible eventOutcomes for xlmresolution?

I think it's "Failure", "Success", 'Mixed"

So far I've seen:

**Comment by lydiam** [comment]
On 5/31/2012 4:05 PM, Carol Chou wrote:

> > What does  eventOutcome mixed mean?  Does that indicate that xmlresolution for file/0 included manifest schema statuses of "success" and "failure" for the same file?
> > 
> > > I think so,  I remember that's what it was discussed.  Mix means that
> > > for a xml file, some schema can be retrieved and some can't.

I wonder specifically about cases where the xmlresolution manifest has 
"success" and "unresolved" statuses, and whether that's going to result 
in eventOutcome of "success" or "mixed".  I suppose that we want it to 
give a "mixed" eventOutcome, in keeping with what appears to be 
happening currently.

**Comment by lydiam** [comment]
My understanding of the current statuses in AIP xmlresolution events:
success - all external schema, dtd, stylesheet references in the specific XML file have been downloaded.
failure - all external schema, dtd, stylesheet references in the specific XML file could not be downloaded.
mixed - some external schema, dtd, stylesheet references in the specific XML file have been downloaded. Others are either unresolvable or could not be downloaded.

**Comment by iterman** [comment]
I believe this is resolved.
