### ISSUE TITLE
invalid premis event

### ISSUE THREAD

**Issue by flazz** [fcla/xmlresolution#2]
i'm getting this error when validating 
    cvc-complex-type.2.4.a: Invalid content was found starting with element 'eventOutcomeDetail'. One of '{"info:lc/xmlns/premis-v2":eventOutcomeInformation, "info:lc/xmlns/premis-v2":linkingAgentIdentifier, "info:lc/xmlns/premis-v2":linkingObjectIdentifier}' is expected

i checked the [schema](http://www.loc.gov/standards/premis/premis.xsd), it seems as if eventOutcomeDetail needs to be inside eventOutcomeInformation

**Comment by grf** [comment]
yes, it needs to be inside and now is.
