### ISSUE TITLE
XMLRESOLUTION  should attempt to resolve DTDs and PIs

### ISSUE THREAD

**Issue by iterman** [fcla/xmlresolution#21]
XMLRESOLUTION  does not attempt to resolve DTDs or Processing Instructions.
So for example if an xml document contains something like:  
<?xml-stylesheet type="text/xsl" href="http://schema.fcla.edu/xml/student_html.xsl"?>,
or
  <!DOCTYPE rss PUBLIC "-//Netscape Communications//DTD RSS 0.91//EN" "http://schema.fcla.edu/xml/rss-0.91.dtd">
or
  <!DOCTYPE rss SYSTEM "http://schema.fcla.edu/xml/rss-0.91.dtd">

these references should be resolved.

**Comment by lydiam** [comment]
XMLResolution does correctly resolve/download dtds and stylesheets, in addition to schemas.
