### ISSUE TITLE
question: why doesn't xmlresolution consider a local stylesheet reference "unresolved"?

### ISSUE THREAD

**Issue by lydiam** [fcla/xmlresolution#24]
I have an XMLresolution test case (a daitss ingest report content file) that contains an href to a local stylesheet.  Why doesn't XMLresolution consider this stylesheet "unresolved"?  The net result is that an XML file references a stylesheet that's not included in the xmlres tarball.

A snippet from the ingest report:

```
 <?xml version="1.0"?>
 <?xml-stylesheet type="text/xsl" href="/daitss2Report.xsd"?>
 <REPORT>
```

The AIP descriptor indicates that xmlresolution for the ingest report content file is a "success", yet the tarball doesn't contain the stylesheet.  Shouldn't this be considered a "failure" or something other than a "success"?

**Comment by lydiam** [comment]
A broader question:  how does XMLresolution determine which references are included in the manifest and which aren't?  Per today's DAITSS meeting it was proposed that XMLresolution at minimum list a local stylesheet in the manifest.xml file as "unresolved".

**Comment by lydiam** [comment]
I believe that it was decided that XML Resolution should process only external references.  Can someone confirm this so that we can close this issue?

**Comment by iterman** [comment]
This question was settled at a group meeting.It was decided it is  the job of XMLResolution to try to resolve only external objects.

This issue can be closed.
