### ISSUE TITLE
AIP descriptor XML Resolution event eventOutcome=error 

### ISSUE THREAD

**Issue by iterman** [fcla/xmlresolution#26]
XML Resolution will populate the the eventOutcome tag with 'error' when the xml document is not well formed.  The controlled vocabulary allows for 'failure'.

**Comment by iterman** [comment]
The eventOutcome tag is only be populated with "failure" in accordance with the controlled vocabulary.
This is true for even for all type of errors like the xml document is not well formed.
This issue should be closed.

**Comment by iterman** [comment]
xml_resolver.rb  was modified to fix this issue.

**Comment by lydiam** [comment]
This appears to be resolved for TestCase8 on ripple.
