### ISSUE TITLE
Running XMLresolution instance relies on files in /var/daitss/tmp to maintain functionality

### ISSUE THREAD

**Issue by childree** [fcla/xmlresolution#28]
Currently, a running instance of XMLresolution service requires all created  collection files in /var/daitss/tmp in order for the service to maintain functionality.  If these files are removed while the instance of XMLresolution is running, it breaks DAITSS with a 500 Internal Service Error.  XMLresolution should not be dependent on any files in /var/daitss/tmp and should clean up after itself.

The following test exemplifies this case:

[user@ripple tmp]$ sudo daitss stop
[sudo] password for user:

```
 Stopping apache services...
 Stopping describe...
 Sending QUIT signal to process 11510 ... 
 Sending QUIT signal to process 11518 ... 
 Stopping pulse...
 Stopping reporter...
```

[user@ripple tmp]$ sudo daitss start

```
 Starting apache services...
 Warning: DocumentRoot [/var/daitss/ops/sharedpackages] does not exist
 Starting description service 1...
 Starting description service 2...
 Starting pulse...
 Starting reporter
```

<b>NOTE:</b> <i>See https://github.com/daitss/core/issues/709 for question about this Warning.</i>

[user@ripple tmp]$ sudo daitss status

```
Apache is running
Description service 1 is running
Description service 2 is running
Pulse is running
Reporter is running
```

[user@ripple tmp]$ ls /var/daitss/tmp/

```
fff  phusion  tivoli
```

[user@ripple tmp]$ sudo -u daitss submit --username **\* --password **\* --source BENCHMARK --package /var/daitss/ops/FDA_benchmarks/ETDs/FDAE001898 --batch Update_Tests --note "Testing that ripple is actually functioning."

[sudo] password for user: 
[user@ripple tmp]$ ls /var/daitss/tmp/

```
d20120926-4041-1vrt95n  fff  phusion  RackMultipart20120926-4017-4d1731-0  RackMultipart20120926-4017-wk2x76-0  tivoli
```

[user@ripple tmp]$ sudo -u daitss rm -r d20120926-4041-1vrt95n
[sudo] password for user: 
[user@ripple tmp]$ ls

```
fff  phusion  RackMultipart20120926-4017-4d1731-0  RackMultipart20120926-4017-wk2x76-0  tivoli
```

[user@ripple tmp]$ sudo -u daitss submit --username **\* --password **\* --source BENCHMARK --package /var/daitss/ops/FDA_benchmarks/ETDs/FDAE001898 --batch Update_Tests --note "Testing that ripple is actually functioning."

Via FDA GUI:
     ingest of EVYLH9JFT_1FW1GT ( error )
     snafu
     time   Wed Sep 26 10:58:35 -0400 2012
     message    

```
 bad status
 http://xmlresolution.ripple.fcla.edu/ieids/EVYLH9JFT_1FW1GT: 500
 500 Internal Service Error - The directory for storing the collections, '/var/daitss/tmp/d20120926-4041-1vrt95n/collections', doesn't exist or is unreadable by this user (daitss) and group (daitss).

 trace  

 /opt/web-services/sites/core/releases/20120921154311/lib/mixin/curb.rb:10:in `error'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/service/xmlres.rb:12:in `put_collection'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/preserve.rb:37:in `preserve'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/journal.rb:16:in `step'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/preserve.rb:35:in `preserve'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/ingest.rb:29:in `ingest'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/process.rb:82:in `send'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/process.rb:82:in `spawn'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/process.rb:66:in `fork'
 /opt/web-services/sites/core/releases/20120921154311/lib/daitss/proc/wip/process.rb:66:in `spawn'
 ./bin/pulse:161:in `start_wips'
 ./bin/pulse:158:in `each'
 ./bin/pulse:158:in `start_wips'
 ./bin/pulse:194
 ./bin/pulse:192:in `loop'
 ./bin/pulse:192
```

[user@ripple tmp]$ ls

```
fff  phusion  RackMultipart20120926-4017-hzoybb-0  RackMultipart20120926-4017-mrhzac-0  tivoli
```

[user@ripple tmp]$ sudo daitss graceful

```
 Gracefully restarting apache...
 Warning: DocumentRoot [/var/daitss/ops/sharedpackages] does not exist
 Stopping pulse...
 Starting pulse...
```

[user@ripple tmp]$ sudo daitss status

```
 Apache is running
 Description service 1 is running
 Description service 2 is running
 Pulse is running
 Reporter is running
```

[user@ripple tmp]$ ls

```
fff  phusion  RackMultipart20120926-4017-hzoybb-0  RackMultipart20120926-4017-mrhzac-0  tivoli
```

[user@ripple tmp]$ ls

```
d20120926-6088-148jkzp  fff  phusion  RackMultipart20120926-4017-hzoybb-0  RackMultipart20120926-4017-mrhzac-0  RackMultipart20120926-6063-10w94h5-0  RackMultipart20120926-6063-dqofe9-0  tivoli
```

<b>NOTE:</b> <i>See https://github.com/daitss/core/issues/509 about retainment of RackMultipart\* files.<i>

**Comment by lydiam** [comment]
My understanding is that the new xmlresolution code on ripple would use /var/daitss/tmp for 
collections and schemas, based on the DAITSS config file, and that 
xmlresolution deletes these directories when no packages being processed 
link to them.  

I wonder if any clearing of /var/daitss/tmp files that 
affect XMLresolution should also be followed by a restart of the 
service. 

 I have some recollection that XMLresolution did "self-cleanup" 
every 24 hours, but that the new code decrements counters on the schemas 
and collections and does cleanup as it goes.  The text that Ira approved 
for this step (in a flowchart I've been working on) is: "decrements 
schema references and deletes Collection" (no mention of deleting schemas).

I think that something may be off on Ripple's setup:

I see the following in /opt/web-services/conf.d/daitss-config.yml:

defaults:
     temp_directory:             /var/daitss/tmp

But also:
xmlresolution.ripple.fcla.edu:
     log_syslog_facility:         LOG_LOCAL0
     data_root: /opt/web-services/sites/xmlresolution/shared
     resolver_proxy:              localhost:3128

[lydiam@ripple shared]$ pwd
/opt/web-services/sites/xmlresolution/shared
[lydiam@ripple shared]$ ls -l
total 46
drwxrwsr-x+ 3 daitss daitss  1024 Jan 18  2011 bundle
drwxrwsr-x+ 6 daitss daitss 33792 Jul 26 14:07 collections
drwxrwsr-x+ 2 daitss daitss  8192 Jun 15 13:16 schemas

What function does   data_root: 
/opt/web-services/sites/xmlresolution/shared  serve?

**Comment by childree** [comment]
data_root = filesystem path to the directory that the web server user has write access

Restarting the service works but it would be best if the service detached itself from those files and cleaned them up when they are not in use.

**Comment by cchou** [comment]
Carol suggests that daitss stop might be enhanced to clear out /var/daitss/tmp as a last step.  That would get rid of the cruft files, and put the same script in /opt/fda so that it could be run manually by an operator when xmlresolution/daitss is down.

**Comment by iterman** [comment]
I see several possible ways to handle this.
1.  We can make the root directory of XMLResolution something other than /var/daitss/tmp.
2.   Whenever we we clean out /var/daitss/tmp  we simply recycle XMLResolution.
3.  Look into the possiblity of changing the XMLResolution code so that whenever it detects that its
working directories do not exist reallocate them dynamically.   This could be tricky  in the case when a
collection has been created, then the job that cleans the temp directories is triggered,  then core requests
a resolution and refers to a collection that no longer exists.

**Comment by iterman** [comment]
I think this issue can be closed. 

 But must be understood that XMLResolution  creates a Ruby sub-directory under /var/daitss/tmp and under  that it  sub-directories ./collections and ./schemas.   The directory structure looks like
/var/daitss/tmp/xxxx
/var/daitss/tmp/xxxx/schemas
/var/daitss/tmp/xxxx/collections

 If any of those directories are  deleted XMLResolution must be restarted.
  Even though they are "temp" directories they are permanent for an instance of XML Resolution.   XMLResolution will delete /var/daitss/xxxx/  automatically when it come down.
