### ISSUE TITLE
amount of items in tarball is non-deterministic

### ISSUE THREAD

**Issue by flazz** [fcla/xmlresolution#4]
sometimes there are 75 items in the tarball, othertimes there is 1 for the same input pacakge

**Comment by grf** [comment]
Franco says it's one particular package
exhibiting the problem; he'll  forward the
example package when the error is next
encountered so that we can reproduce
the error.

**Comment by grf** [comment]
Not only non-deterministic - it's non-repeatable.   Reopen if it resurfaces.
